#!/usr/bin/env bash
# A bash script that installs nginx on server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
