#!/usr/bin/env bash
# Install nginx on your web-01 server using curl
# Nginx should be listening on port 80

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
