#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"
# Update the system
sudo apt update
sudo apt upgrade -y

# Install Nginx
sudo apt install nginx -y

# Configure the redirection
sudo tee /etc/nginx/conf.d/redirect.conf > /dev/null <<EOT
server {
    listen 80;
    ubuntu masino.tech;

    location /redirect_me {
        return 301 https://github.com/JohnsonMasino;
    }
}
EOT

# Restart Nginx
sudo systemctl restart nginx

