#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to my github page.
# The redirection is configured as a "301 Moved Permanently" message

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello Word!" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://github.com/JohnsonMasino;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
