#!/usr/bin/env bash
# I am invincible!!! when receiving a SIGTERM signal.
# displays 'To infinity and beyond' indefinitely.
# With a sleep 2 in between each iteration

while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
