#!/usr/bin/env bash
# Running nginx as nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
su nginx -s /bin/bash -c '/etc/init.d/nginx restart'
